In [1]:
# Dependencies
import requests
import json
import pandas as pd

base_url = "https://pokeapi.co/api/v2/pokemon/"

kelli_lst = []

for i in range(150):
    url = base_url+str(i+1)
    response = requests.get(url).json()
    
    location = requests.get(response["location_area_encounters"]).json()
    if len(location) ==0:
        location="Whitechapel"
    else:
        location = location[0]["location_area"]["name"]
     
        
    kelli_lst.append({
        "Pokemon name": response["name"],
        "Weight": response["weight"],
        "Fighting type" : response["types"][0]["type"]["name"],
        "Height": response["height"],
        "Main ability": response["abilities"][0]["ability"]["name"],
        "Attack": response["stats"][1]["base_stat"],
        "Defense": response["stats"][2]["base_stat"],
        "Type of Move":response["moves"][0]["move"]["name"],
        "Region": location
    })


    print(f"processing {i}")

final_df = pd.DataFrame(kelli_lst)
final_df

processing 0
processing 1
processing 2
processing 3
processing 4
processing 5
processing 6
processing 7
processing 8
processing 9
processing 10
processing 11
processing 12
processing 13
processing 14
processing 15
processing 16
processing 17
processing 18
processing 19
processing 20
processing 21
processing 22
processing 23
processing 24
processing 25
processing 26
processing 27
processing 28
processing 29
processing 30
processing 31
processing 32
processing 33
processing 34
processing 35
processing 36
processing 37
processing 38
processing 39
processing 40
processing 41
processing 42
processing 43
processing 44
processing 45
processing 46
processing 47
processing 48
processing 49
processing 50
processing 51
processing 52
processing 53
processing 54
processing 55
processing 56
processing 57
processing 58
processing 59
processing 60
processing 61
processing 62
processing 63
processing 64
processing 65
processing 66
processing 67
processing 68
processing 69
processing 70
processing 71
processing 72
processing 73
processing 74
processing 75
processing 76
processing 77
processing 78
processing 79
processing 80
processing 81
processing 82
processing 83
processing 84
processing 85
processing 86
processing 87
processing 88
processing 89
processing 90
processing 91
processing 92
processing 93
processing 94
processing 95
processing 96
processing 97
processing 98
processing 99
processing 100
processing 101
processing 102
processing 103
processing 104
processing 105
processing 106
processing 107
processing 108
processing 109
processing 110
processing 111
processing 112
processing 113
processing 114
processing 115
processing 116
processing 117
processing 118
processing 119
processing 120
processing 121
processing 122
processing 123
processing 124
processing 125
processing 126
processing 127
processing 128
processing 129
processing 130
processing 131
processing 132
processing 133
processing 134
processing 135
processing 136
processing 137
processing 138
processing 139
processing 140
processing 141
processing 142
processing 143
processing 144
processing 145
processing 146
processing 147
processing 148
processing 149

,Pokemon name,Weight,Fighting type,Height,Main ability,Attack,Defense,Type of Move,Region
0,bulbasaur,69,grass,7,overgrow,49,49,razor-wind,cerulean-city-area
1,ivysaur,130,grass,10,overgrow,62,63,swords-dance,Whitechapel
2,venusaur,1000,grass,20,overgrow,82,83,swords-dance,Whitechapel
3,charmander,85,fire,6,blaze,52,43,mega-punch,pallet-town-area
4,charmeleon,190,fire,11,blaze,64,58,mega-punch,Whitechapel
...,...,...,...,...,...,...,...,...,...
145,moltres,600,fire,20,pressure,100,90,razor-wind,mt-silver-top
146,dratini,33,dragon,18,shed-skin,64,45,bind,mt-coronet-4f
147,dragonair,165,dragon,40,shed-skin,84,65,bind,mt-coronet-4f
148,dragonite,2100,dragon,22,inner-focus,134,95,mega-punch,dragonspiral-tower-outside
149,mewtwo,1220,psychic,20,pressure,110,90,mega-punch,cerulean-cave-b1f

In [4]:
#counting number of cities for each
final_df["Region"].value_counts()

Whitechapel               20
sinnoh-route-225-area      7
eterna-forest-area         5
canalave-city-area         5
sinnoh-route-224-area      4
                          ..
celadon-city-area          1
valley-windworks-area      1
undella-bay-area           1
turnback-cave-pillar-1     1
cerulean-cave-b1f          1
Name: Region, Length: 75, dtype: int64

In [3]:
#Creates a csv file with info from dataframe

#final_df.to_csv("location.csv", index=False)

In [21]:
#Locate the csv file
location_path = "location_with_lat_long.csv"

In [22]:
#Read the csv file
location_data = pd.read_csv(location_path)

In [23]:
#output dataframe from csv file
location_data

    Pokemon name  Latitude  Longitude
0      bulbasaur    6.8428    81.3399
1        ivysaur   51.5148     0.0651
2       venusaur   51.5148     0.0651
3     charmander    7.2936    80.6413
4     charmeleon   51.5148     0.0651
..           ...       ...        ...
145      moltres   50.4155   -15.0737
146      dratini   39.9042   116.4074
147    dragonair   39.9042   116.4074
148    dragonite   50.3755    -4.1427
149       mewtwo   28.7041    77.1025

[150 rows x 3 columns]

In [24]:
#Merge the dataframe with latitude and longitude to final_df
merge_df = pd.merge(final_df, location_data, on="Pokemon name", how ='left')
merge_df

,Pokemon name,Weight,Fighting type,Height,Main ability,Attack,Defense,Type of Move,Region,Latitude,Longitude
0,bulbasaur,69,grass,7,overgrow,49,49,razor-wind,cerulean-city-area,6.8428,81.3399
1,ivysaur,130,grass,10,overgrow,62,63,swords-dance,Whitechapel,51.5148,0.0651
2,venusaur,1000,grass,20,overgrow,82,83,swords-dance,Whitechapel,51.5148,0.0651
3,charmander,85,fire,6,blaze,52,43,mega-punch,pallet-town-area,7.2936,80.6413
4,charmeleon,190,fire,11,blaze,64,58,mega-punch,Whitechapel,51.5148,0.0651
...,...,...,...,...,...,...,...,...,...,...,...
145,moltres,600,fire,20,pressure,100,90,razor-wind,mt-silver-top,50.4155,-15.0737
146,dratini,33,dragon,18,shed-skin,64,45,bind,mt-coronet-4f,39.9042,116.4074
147,dragonair,165,dragon,40,shed-skin,84,65,bind,mt-coronet-4f,39.9042,116.4074
148,dragonite,2100,dragon,22,inner-focus,134,95,mega-punch,dragonspiral-tower-outside,50.3755,-4.1427
149,mewtwo,1220,psychic,20,pressure,110,90,mega-punch,cerulean-cave-b1f,28.7041,77.1025